"""empty message

Revision ID: 56817166d159
Revises: 6779b69baa6d
Create Date: 2025-04-26 14:18:17.273042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56817166d159'
down_revision = '6779b69baa6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint('people_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('people_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
